name: Restore cached seggerx dependencies or download them
description: Restore cached seggerx dependencies or download them

runs:
  using: "composite"
  steps:
    - name: Restore cached seggerx dependency sources
      id: cache-seggerx
      uses: actions/cache@v4
      with:
        path: |
          src/bundles/segger/seggerx_2024_08_12.tar.gz
        key: seggerx-source-zip-file

    - name: Fetch seggerx
      shell: bash
      if: ${{ steps.cache-seggerx.outputs.cache-hit != 'true' }}
      run: |
        curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/segger/seggerx_2024_08_12.tar.gz
        mv seggerx* src/bundles/segger/
