name: Download Mac ChimeraXes
description: Download Mac ChimeraXes for merging Mac builds into a universal build

inputs:
  cache_key:
    description: remote cache key
    required: true
  build_type:
    description: what kind of build to download
    required: true

runs:
  using: "composite"
  steps:
    - name: Mask input parameters
      shell: bash
      run: |
        export PREBUILT_CACHE_KEY=${{ inputs.cache_key }}
        echo "::add-mask::$PREBUILT_CACHE_KEY"

    - name: Fetch the builds
      shell: bash
      run: |
        export CHIMERAX_AMD64_URL="https://preview.rbvi.ucsf.edu/chimerax/cgi-bin/get_cx_action.py?platform=macosx&build_type=${{ inputs.build_type }}&architecture=x86_64"
        export CHIMERAX_ARM64_URL="https://preview.rbvi.ucsf.edu/chimerax/cgi-bin/get_cx_action.py?platform=macosx&build_type=${{ inputs.build_type }}&architecture=arm64"
        curl -H "X-API-KEY: ${{ inputs.cache_key }}" ${CHIMERAX_AMD64_URL} -O -J
        mv chimerax-${{ inputs.build_type}}.dmg chimerax_intel.dmg
        curl -H "X-API-KEY: ${{ inputs.cache_key }}" ${CHIMERAX_ARM64_URL} -O -J
        mv chimerax-${{ inputs.build_type}}.dmg chimerax_arm.dmg
