PIP	= $(PYTHON_EXE) -m pip --log pip.log
PIP_INSTALL = $(PIP) install --use-feature=2020-resolver --upgrade-strategy only-if-needed --no-warn-script-location
APP_PIP	= $(APP_PYTHON_EXE) -m pip --log pip.log
APP_PIP_INSTALL = $(APP_PIP) install --use-feature=2020-resolver --upgrade-strategy only-if-needed --no-warn-script-location
ifeq ($(OS),Darwin)
PIP_INSTALL	+= --no-binary lxml
APP_PIP_INSTALL += --no-binary lxml
endif
