ifdef UV_BUILD
PIP	= $(PYTHON_EXE) -m uv pip
APP_PIP	= $(APP_PYTHON_EXE) -m uv pip
else
PIP	= $(PYTHON_EXE) -m pip
APP_PIP	= $(APP_PYTHON_EXE) -m pip
endif
PIP_INSTALL = $(PIP) install
APP_PIP_INSTALL = $(APP_PIP) install
