import os
import sys
import tomllib

PIPS_DIR = os.path.dirname(os.path.abspath(__file__))
TOP_DIR = os.path.dirname(os.path.dirname(PIPS_DIR))
PPTOML = os.path.join(TOP_DIR, "pyproject.toml")
ARTXT = os.path.join(PIPS_DIR, "app_requirements.txt")

print(PIPS_DIR)
print(TOP_DIR)

with open(PPTOML, "r") as f:
    pyproject = tomllib.loads(f.read())


with open("app_requirements.txt", "w") as f:
    f.write(f"""\
# This file is automatically generated. To edit dependency versions, edit the
# pyproject.toml file at the project root.\n""")

    for dep_category, deplist in pyproject["project"]["optional-dependencies"].items():
        for dep in deplist:
            f.write(dep + '\n')
