name: Restore cached mmtf dependencies or download them
description: Restore cached mmtf dependencies or download them

runs:
  using: "composite"
  steps:
    - name: Restore cached mmtf dependency sources
      id: cache-mmtf
      uses: actions/cache@v4
      with:
        path: |
          src/bundles/mmtf/mmtf-cpp-1.1.0.zip
          src/bundles/mmtf/msgpack-c-cpp-4.1.2.zip
        key: mmtf-source-zip-file

    - name: Fetch PyQt
      shell: bash
      if: ${{ steps.cache-mmtf.outputs.cache-hit != 'true' }}
      run: |
        curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/mmtf/msgpack-c-cpp-4.1.2.zip
        curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/mmtf/mmtf-cpp-1.1.0.zip
        mv mmtf*.zip src/bundles/mmtf/
        mv msgpack*.zip src/bundles/mmtf/
