change_in_items_inspection: &change_in_items_inspection
  - "src/bundles/items_inspection/**"
change_in_bumps: &change_in_bumps
  - "src/bundles/bumps/**"
change_in_model_panel: &change_in_model_panel
  - "src/bundles/model_panel/**"
change_in_toolshed_utils: &change_in_toolshed_utils
  - "src/bundles/toolshed_utils/**"
change_in_rest_server: &change_in_rest_server
  - "src/bundles/rest_server/**"
change_in_neuron: &change_in_neuron
  - "src/bundles/neuron/**"
change_in_preset_mgr: &change_in_preset_mgr
  - "src/bundles/preset_mgr/**"
change_in_sel_inspector: &change_in_sel_inspector
  - "src/bundles/sel_inspector/**"
change_in_remote_control: &change_in_remote_control
  - "src/bundles/remote_control/**"
change_in_ui: &change_in_ui
  - "src/bundles/ui/**"
change_in_chem_group: &change_in_chem_group
  - "src/bundles/chem_group/**"
change_in_render_by_attr: &change_in_render_by_attr
  - "src/bundles/render_by_attr/**"
change_in_model_series: &change_in_model_series
  - "src/bundles/model_series/**"
change_in_crystal_contacts: &change_in_crystal_contacts
  - "src/bundles/crystal_contacts/**"
change_in_profile_grids: &change_in_profile_grids
  - "src/bundles/profile_grids/**"
change_in_connect_structure: &change_in_connect_structure
  - "src/bundles/connect_structure/**"
change_in_registration: &change_in_registration
  - "src/bundles/registration/**"
change_in_swap_res: &change_in_swap_res
  - "src/bundles/swap_res/**"
change_in_dssp: &change_in_dssp
  - "src/bundles/dssp/**"
change_in_exp_cmd: &change_in_exp_cmd
  - "src/bundles/exp_cmd/**"
change_in_phenix_ui: &change_in_phenix_ui
  - "src/bundles/phenix_ui/**"
change_in_residue_fit: &change_in_residue_fit
  - "src/bundles/residue_fit/**"
change_in_movie: &change_in_movie
  - "src/bundles/movie/**"
change_in_scenes: &change_in_scenes
  - "src/bundles/scenes/**"
change_in_shape: &change_in_shape
  - "src/bundles/shape/**"
change_in_md_crds: &change_in_md_crds
  - "src/bundles/md_crds/**"
change_in_looking_glass: &change_in_looking_glass
  - "src/bundles/looking_glass/**"
change_in_renumber_residues: &change_in_renumber_residues
  - "src/bundles/renumber_residues/**"
change_in_core_formats: &change_in_core_formats
  - "src/bundles/core_formats/**"
change_in_linux_support: &change_in_linux_support
  - "src/bundles/linux_support/**"
change_in_cage_builder: &change_in_cage_builder
  - "src/bundles/cage_builder/**"
change_in_clashes: &change_in_clashes
  - "src/bundles/clashes/**"
change_in_webservices: &change_in_webservices
  - "src/bundles/webservices/**"
change_in_change_chains: &change_in_change_chains
  - "src/bundles/change_chains/**"
change_in_core: &change_in_core
  - "src/bundles/core/**"
change_in_buttons: &change_in_buttons
  - "src/bundles/buttons/**"
change_in_data_formats: &change_in_data_formats
  - "src/bundles/data_formats/**"
change_in_sdf: &change_in_sdf
  - "src/bundles/sdf/**"
change_in_vrml: &change_in_vrml
  - "src/bundles/vrml/**"
change_in_test: &change_in_test
  - "src/bundles/test/**"
change_in_emdb_sff: &change_in_emdb_sff
  - "src/bundles/emdb_sff/**"
change_in_foldseek: &change_in_foldseek
  - "src/bundles/foldseek/**"
change_in_show_sequences: &change_in_show_sequences
  - "src/bundles/show_sequences/**"
change_in_markers: &change_in_markers
  - "src/bundles/markers/**"
change_in_map_filter: &change_in_map_filter
  - "src/bundles/map_filter/**"
change_in_basic_actions: &change_in_basic_actions
  - "src/bundles/basic_actions/**"
change_in_struts: &change_in_struts
  - "src/bundles/struts/**"
change_in_mmcif: &change_in_mmcif
  - "src/bundles/mmcif/**"
change_in_bild: &change_in_bild
  - "src/bundles/bild/**"
change_in_save_command: &change_in_save_command
  - "src/bundles/save_command/**"
change_in_nifti: &change_in_nifti
  - "src/bundles/nifti/**"
change_in_help_viewer: &change_in_help_viewer
  - "src/bundles/help_viewer/**"
change_in_tug: &change_in_tug
  - "src/bundles/tug/**"
change_in_shell: &change_in_shell
  - "src/bundles/shell/**"
change_in_imod: &change_in_imod
  - "src/bundles/imod/**"
change_in_add_charge: &change_in_add_charge
  - "src/bundles/add_charge/**"
change_in_axes_planes: &change_in_axes_planes
  - "src/bundles/axes_planes/**"
change_in_morph: &change_in_morph
  - "src/bundles/morph/**"
change_in_tape_measure: &change_in_tape_measure
  - "src/bundles/tape_measure/**"
change_in_color_key: &change_in_color_key
  - "src/bundles/color_key/**"
change_in_maestro: &change_in_maestro
  - "src/bundles/maestro/**"
change_in_modeller: &change_in_modeller
  - "src/bundles/modeller/**"
change_in_alignment_headers: &change_in_alignment_headers
  - "src/bundles/alignment_headers/**"
change_in_volume_menu: &change_in_volume_menu
  - "src/bundles/volume_menu/**"
change_in_zone: &change_in_zone
  - "src/bundles/zone/**"
change_in_segment: &change_in_segment
  - "src/bundles/segment/**"
change_in_amber_info: &change_in_amber_info
  - "src/bundles/amber_info/**"
change_in_diffplot: &change_in_diffplot
  - "src/bundles/diffplot/**"
change_in_task_manager: &change_in_task_manager
  - "src/bundles/task_manager/**"
change_in_atomic_lib: &change_in_atomic_lib
  - "src/bundles/atomic_lib/**"
change_in_io: &change_in_io
  - "src/bundles/io/**"
change_in_bond_rot: &change_in_bond_rot
  - "src/bundles/bond_rot/**"
change_in_pdb_bio: &change_in_pdb_bio
  - "src/bundles/pdb_bio/**"
change_in_toolbar: &change_in_toolbar
  - "src/bundles/toolbar/**"
change_in_bogus: &change_in_bogus
  - "src/bundles/bogus/**"
change_in_mouse_modes: &change_in_mouse_modes
  - "src/bundles/mouse_modes/**"
change_in_label: &change_in_label
  - "src/bundles/label/**"
change_in_bundle_builder: &change_in_bundle_builder
  - "src/bundles/bundle_builder/**"
change_in_rotamer_libs: &change_in_rotamer_libs
  - "src/bundles/rotamer_libs/**"
change_in_surface: &change_in_surface
  - "src/bundles/surface/**"
change_in_cmd_line: &change_in_cmd_line
  - "src/bundles/cmd_line/**"
change_in_gltf: &change_in_gltf
  - "src/bundles/gltf/**"
change_in_wavefront_obj: &change_in_wavefront_obj
  - "src/bundles/wavefront_obj/**"
change_in_crystal: &change_in_crystal
  - "src/bundles/crystal/**"
change_in_hbonds: &change_in_hbonds
  - "src/bundles/hbonds/**"
change_in_vive: &change_in_vive
  - "src/bundles/vive/**"
change_in_stl: &change_in_stl
  - "src/bundles/stl/**"
change_in_hkcage: &change_in_hkcage
  - "src/bundles/hkcage/**"
change_in_build_structure: &change_in_build_structure
  - "src/bundles/build_structure/**"
change_in_atomic: &change_in_atomic
  - "src/bundles/atomic/**"
change_in_speech: &change_in_speech
  - "src/bundles/speech/**"
change_in_nrrd: &change_in_nrrd
  - "src/bundles/nrrd/**"
change_in_pdb_matrices: &change_in_pdb_matrices
  - "src/bundles/pdb_matrices/**"
change_in_file_history: &change_in_file_history
  - "src/bundles/file_history/**"
change_in_pdb_images: &change_in_pdb_images
  - "src/bundles/pdb_images/**"
change_in_medical_imaging: &change_in_medical_imaging
  - "src/bundles/medical_imaging/**"
change_in_ihm: &change_in_ihm
  - "src/bundles/ihm/**"
change_in_nih_presets: &change_in_nih_presets
  - "src/bundles/nih_presets/**"
change_in_lighting_gui: &change_in_lighting_gui
  - "src/bundles/lighting_gui/**"
change_in_mask: &change_in_mask
  - "src/bundles/mask/**"
change_in_iupac: &change_in_iupac
  - "src/bundles/iupac/**"
change_in_map: &change_in_map
  - "src/bundles/map/**"
change_in_centroids: &change_in_centroids
  - "src/bundles/centroids/**"
change_in_blastprotein: &change_in_blastprotein
  - "src/bundles/blastprotein/**"
change_in_meeting: &change_in_meeting
  - "src/bundles/meeting/**"
change_in_vtk: &change_in_vtk
  - "src/bundles/vtk/**"
change_in_unit_cell: &change_in_unit_cell
  - "src/bundles/unit_cell/**"
change_in_check_waters: &change_in_check_waters
  - "src/bundles/check_waters/**"
change_in_crosslinks: &change_in_crosslinks
  - "src/bundles/crosslinks/**"
change_in_altloc_explorer: &change_in_altloc_explorer
  - "src/bundles/altloc_explorer/**"
change_in_arrays: &change_in_arrays
  - "src/bundles/arrays/**"
change_in_function_key: &change_in_function_key
  - "src/bundles/function_key/**"
change_in_alphafold: &change_in_alphafold
  - "src/bundles/alphafold/**"
change_in_smooth_lines: &change_in_smooth_lines
  - "src/bundles/smooth_lines/**"
change_in_color_actions: &change_in_color_actions
  - "src/bundles/color_actions/**"
change_in_deep_mutational_scan: &change_in_deep_mutational_scan
  - "src/bundles/deep_mutational_scan/**"
change_in_shortcuts: &change_in_shortcuts
  - "src/bundles/shortcuts/**"
change_in_nucleotides: &change_in_nucleotides
  - "src/bundles/nucleotides/**"
change_in_positions: &change_in_positions
  - "src/bundles/positions/**"
change_in_atom_search: &change_in_atom_search
  - "src/bundles/atom_search/**"
change_in_segger: &change_in_segger
  - "src/bundles/segger/**"
change_in_dist_monitor: &change_in_dist_monitor
  - "src/bundles/dist_monitor/**"
change_in_mcopy: &change_in_mcopy
  - "src/bundles/mcopy/**"
change_in_medical_toolbar: &change_in_medical_toolbar
  - "src/bundles/medical_toolbar/**"
change_in_sim_matrices: &change_in_sim_matrices
  - "src/bundles/sim_matrices/**"
change_in_sideview: &change_in_sideview
  - "src/bundles/sideview/**"
change_in_log: &change_in_log
  - "src/bundles/log/**"
change_in_cellpack: &change_in_cellpack
  - "src/bundles/cellpack/**"
change_in_to_quest: &change_in_to_quest
  - "src/bundles/to_quest/**"
change_in_tug_ligands: &change_in_tug_ligands
  - "src/bundles/tug_ligands/**"
change_in_image_formats: &change_in_image_formats
  - "src/bundles/image_formats/**"
change_in_uniprot: &change_in_uniprot
  - "src/bundles/uniprot/**"
change_in_pick_blobs: &change_in_pick_blobs
  - "src/bundles/pick_blobs/**"
change_in_read_pbonds: &change_in_read_pbonds
  - "src/bundles/read_pbonds/**"
change_in_match_maker: &change_in_match_maker
  - "src/bundles/match_maker/**"
change_in_spacenavigator: &change_in_spacenavigator
  - "src/bundles/spacenavigator/**"
change_in_pdb_lib: &change_in_pdb_lib
  - "src/bundles/pdb_lib/**"
change_in_viperdb: &change_in_viperdb
  - "src/bundles/viperdb/**"
change_in_geometry: &change_in_geometry
  - "src/bundles/geometry/**"
change_in_segmentations: &change_in_segmentations
  - "src/bundles/segmentations/**"
change_in_map_data: &change_in_map_data
  - "src/bundles/map_data/**"
change_in_map_eraser: &change_in_map_eraser
  - "src/bundles/map_eraser/**"
change_in_rna_layout: &change_in_rna_layout
  - "src/bundles/rna_layout/**"
change_in_mol2: &change_in_mol2
  - "src/bundles/mol2/**"
change_in_std_commands: &change_in_std_commands
  - "src/bundles/std_commands/**"
change_in_seqalign: &change_in_seqalign
  - "src/bundles/seqalign/**"
change_in_color_globe: &change_in_color_globe
  - "src/bundles/color_globe/**"
change_in_graphics: &change_in_graphics
  - "src/bundles/graphics/**"
change_in_swapaa: &change_in_swapaa
  - "src/bundles/swapaa/**"
change_in_leap_motion: &change_in_leap_motion
  - "src/bundles/leap_motion/**"
change_in_esmfold: &change_in_esmfold
  - "src/bundles/esmfold/**"
change_in_alignment_algs: &change_in_alignment_algs
  - "src/bundles/alignment_algs/**"
change_in_rotamers: &change_in_rotamers
  - "src/bundles/rotamers/**"
change_in_list_info: &change_in_list_info
  - "src/bundles/list_info/**"
change_in_coulombic: &change_in_coulombic
  - "src/bundles/coulombic/**"
change_in_mole: &change_in_mole
  - "src/bundles/mole/**"
change_in_nmrstar: &change_in_nmrstar
  - "src/bundles/nmrstar/**"
change_in_webcam: &change_in_webcam
  - "src/bundles/webcam/**"
change_in_dicom: &change_in_dicom
  - "src/bundles/dicom/**"
change_in_topography: &change_in_topography
  - "src/bundles/topography/**"
change_in_pubchem: &change_in_pubchem
  - "src/bundles/pubchem/**"
change_in_scheme_mgr: &change_in_scheme_mgr
  - "src/bundles/scheme_mgr/**"
change_in_map_series: &change_in_map_series
  - "src/bundles/map_series/**"
change_in_realsense: &change_in_realsense
  - "src/bundles/realsense/**"
change_in_storm: &change_in_storm
  - "src/bundles/storm/**"
change_in_pdb: &change_in_pdb
  - "src/bundles/pdb/**"
change_in_seq_view: &change_in_seq_view
  - "src/bundles/seq_view/**"
change_in_signal_viewer: &change_in_signal_viewer
  - "src/bundles/signal_viewer/**"
change_in_open_command: &change_in_open_command
  - "src/bundles/open_command/**"
change_in_mmtf: &change_in_mmtf
  - "src/bundles/mmtf/**"
change_in_struct_measure: &change_in_struct_measure
  - "src/bundles/struct_measure/**"
change_in_animations: &change_in_animations
  - "src/bundles/animations/**"
change_in_orthopick: &change_in_orthopick
  - "src/bundles/orthopick/**"
change_in_bug_reporter: &change_in_bug_reporter
  - "src/bundles/bug_reporter/**"
change_in_mlp: &change_in_mlp
  - "src/bundles/mlp/**"
change_in_interfaces: &change_in_interfaces
  - "src/bundles/interfaces/**"
change_in_addh: &change_in_addh
  - "src/bundles/addh/**"
change_in_smiles: &change_in_smiles
  - "src/bundles/smiles/**"
change_in_map_fit: &change_in_map_fit
  - "src/bundles/map_fit/**"
change_in_viewdockx: &change_in_viewdockx
  - "src/bundles/viewdockx/**"
change_in_dock_prep: &change_in_dock_prep
  - "src/bundles/dock_prep/**"
