# === UCSF ChimeraX Copyright ===
# Copyright 2016 Regents of the University of California.
# All rights reserved.  This software provided pursuant to a
# license agreement containing restrictions on its disclosure,
# duplication and use.  For details see:
# http://www.rbvi.ucsf.edu/chimerax/docs/licensing.html
# This notice must be embedded in or attached to all copies,
# including partial copies, of the software or any revisions
# or derivations thereof.
# === UCSF ChimeraX Copyright ===

PREREQ_MAKE = 1
TOP = ../../../..
include $(TOP)/mk/config.make

include Makefile.common

QUOTE_CC := $(subst ','\'',$(CFLAGS) $(TARGET_ARCH))
QUOTE_CXX := $(subst ','\'',$(CXXFLAGS) $(TARGET_ARCH))

# Make xdrfile use our compiler options
ifneq ($(filter $(MSYSTEM),MSYS MINGW64),)
ENV_CONFIGURE =
else
ENV_CONFIGURE = CFLAGS='$(QUOTE_CC)' CXXFLAGS='$(QUOTE_CXX)' LDFLAGS="$(TARGET_ARCH) $(LDFLAGS)"
endif

PATCHES = patch

all: $(XDRFILE_LIB)

$(XDRFILE_LIB): $(XDRFILE_LIB_SOURCE)
	cd $(XDRFILE_LIB_SOURCE) ; $(MAKE)

$(XDRFILE_LIB_SOURCE):
	tar zxf $(XDRFILE_ARCHIVE)
	cd $(XDRFILE_LIB_SOURCE) && autoreconf -fiv
ifneq ($(PATCHES),)
	for p in $(PATCHES); do \
		if [ -f $$p ] ; then \
			(cd $(XDRFILE_LIB_SOURCE) ; patch -p0) < $$p ; \
		fi ; \
	done
endif
ifneq ($(filter $(MSYSTEM),MSYS MINGW64),)
	# Though it says 'mingw32' inspection of the generated static library shows x86_64
	cd $(XDRFILE_LIB_SOURCE) ; env $(ENV_CONFIGURE) ./configure --build=x86_64-w64-mingw32 --enable-shared --with-pic
else
	cd $(XDRFILE_LIB_SOURCE) ; env $(ENV_CONFIGURE) ./configure --enable-shared --with-pic
endif

clean:
	rm -rf $(PYMOD) $(OBJS) $(XDRFILE_LIB_SOURCE) $(BUILD)
ifdef WIN32
	rm -f $(PYMOD_NAME).exp $(PYMOD_NAME).lib
endif
