# === UCSF ChimeraX Copyright ===
# Copyright 2016 Regents of the University of California.
# All rights reserved.  This software provided pursuant to a
# license agreement containing restrictions on its disclosure,
# duplication and use.  For details see:
# http://www.rbvi.ucsf.edu/chimerax/docs/licensing.html
# This notice must be embedded in or attached to all copies,
# including partial copies, of the software or any revisions
# or derivations thereof.
# === UCSF ChimeraX Copyright ===

XDRFILE_VERSION = 1.1
XDRFILE_MINOR_VERSION = b
XDRFILE_LIB_SOURCE = xdrfile-$(XDRFILE_VERSION)$(XDRFILE_MINOR_VERSION)
XDRFILE_ARCHIVE = xdrfile-$(XDRFILE_VERSION).tar.gz
XDRFILE_LIB = $(XDRFILE_LIB_SOURCE)/src/.libs/libxdrfile.$(LIB_EXT)
