TOP= ../../../../..
include $(TOP)/mk/config.make

RESDIR = $(datadir)/idatm

install:
	-mkdir $(RESDIR)
	-mkdir $(RESDIR)/templates
	cp templates/FORMAT templates/*.idatmres $(RESDIR)/templates

clean:
