# vim: set expandtab shiftwidth=4 softtabstop=4:

# === UCSF ChimeraX Copyright ===
# Copyright 2022 Regents of the University of California. All rights reserved.
# The ChimeraX application is provided pursuant to the ChimeraX license
# agreement, which covers academic and commercial uses. For more details, see
# <https://www.rbvi.ucsf.edu/chimerax/docs/licensing.html>
#
# This particular file is part of the ChimeraX library. You can also
# redistribute and/or modify it under the terms of the GNU Lesser General
# Public License version 2.1 as published by the Free Software Foundation.
# For more details, see
# <https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html>
#
# THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER
# EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. ADDITIONAL LIABILITY
# LIMITATIONS ARE DESCRIBED IN THE GNU LESSER GENERAL PUBLIC LICENSE
# VERSION 2.1
#
# This notice must be embedded in or attached to all copies, including partial
# copies, of the software or any revisions or derivations thereof.
# === UCSF ChimeraX Copyright ==

import os

def save_dms(session, filename: str, surface=None):
    """
    Save a molecular surface to a DMS file.

    Parameters:
        session (chimerax.core.session.Session): ChimeraX session.
        filename (str): Output DMS filename.
        surface (chimerax.atomic.Structure | None): Surface model to export.
    """
    if not surface:
        from chimerax.surface import get_surface_models
        surfaces = get_surface_models(session)
        if not surfaces:
            session.logger.warning("No surfaces found to save.")
            return
        surface = surfaces[0]  # Default: first surface model

    with open(filename, 'w') as f:
        write_dms(surface, f)
    session.logger.info(f"Saved DMS file: {filename}")


def write_dms(surface, f):
    """
    Write the surface model to a DMS file.

    Parameters:
        surface (chimerax.atomic.Structure): Surface model.
        f (file object): Opened file to write.
    """
    f.write("# DMS file generated by ChimeraX\n")
    for v in surface.vertices:
        f.write(f"V {v[0]:.3f} {v[1]:.3f} {v[2]:.3f}\n")
    for t in surface.triangles:
        f.write(f"T {t[0]} {t[1]} {t[2]}\n")
