.TH CHIMERAX 1 2018-6-28
.SH NAME
chimerax \- molecular visualization
.SH SYNOPSIS
.B chimerax
[\fIoptions\fP]
[\fIdata-files\fP]
.SH DESCRIPTION
.B ChimeraX
is a molecular visualization program from the Resource for Biocomputing, Visualization, and Informatics (RBVI),
\fBhttps://www.rbvi.ucsf.edu/chimerax/\fP.
It can be used interactively, in "nogui" mode, or scripted.
If \fIdata-files\fP are given,
then they are opened before control is turned over to the user or script.
The \fIdata-files\fP are given with the same syntax as the filename argument
of chimerax's \fBopen\fP command.
.SH OPTIONS
.TP
.B --help
Show all command line arguments.
.TP
.B --nogui
Turn off the gui
.TP
.B --offscreen
On Linux.  In nogui mode, try to use an offscreen framebuffer so images can be saved.
.TP
.B --stereo
Starting with graphics in quad-buffered stereo mode.
.TP
.B --listioformats
Show all recognized file suffixes and if they can be opened and/or saved.
.TP
.B --silent
Don't output startup splash text and otherwise refrain from being verbose.
.TP
.B --nostatus
Don't output to status line.
.TP
.B --notools
Do not autostart any tools at startup.
.TP
.BI --start\  tool_name
Start the named tool during ChimeraX startup after the autostart tools.
.TP
.BI --cmd\  command
Run the ChimeraX command at startup after starting tools.
.TP
.B --exit
Exit after processing command line arguments.
.TP
.BI --script\  "python script and arguments"
Run the given script with sys.argv set to the given \fIarguments\fP.
The \fIarguments\fP are parse as if they were on the ChimeraX command line.
.TP
.B --uninstall
If needed, deregister any icons or mime types,
then remove as much of the installation directory as possible.
.TP
.B --usedefaults
Ignore user settings and use default settings.
.TP
.B --version
Print out current version.
If given two times,
then all of installed ChimeraX tools versions are listed.
If given three times,
then all of installed Python package versions are listed.
.TP
.B --color
.br
.B --nocolor
In nogui mode, explicitly choose whether color is used for logging output types.
Otherwise, if the output is a terminal, it is in color.
.TP
.BI -m\  module
Only recognized if it is the first argument.
Act like the Python interpreter and run the module as the main module
and the rest of the arguments are in :py:obj:`sys.argv`.
Implies ``--nogui`` and ``--silent``.
The module name is ``__main__`` instead of a sandbox name that
is used for normal :py:mod:`~chimerax.core.scripting`.
.TP
.BI -c\  command
.br
.BI "-u -c\ " command
Only recognized if it is the first argument.
Act like the Python interpreter and run the command
with the rest of the arguments in :py:obj:`sys.argv`.
Implies ``--nogui`` and ``--silent``.
This is done after ChimeraX has started up, so a ChimeraX session
is available in the global variable ``session``.
.TP
.B --debug
Turn on debugging code.
.TP
.B --lineprofile
Turn on line profiling.  See ChimeraX Programming Manual for more information.
.SH "EXIT STATUS"
If the \fB--exit\fP option is given, and there is a traceback, the exit status will be non-zero.
.SH ENVIRONMENT
.TP
.B CHIMERAX_START
Set a directory to look for Python files to execute and modules to import at startup.
Defaults to \fB~/chimerax_start\fP.
.SH FILES
.TP
.B ~/Downloads/ChimeraX
Directory for downloaded data files that could be useful for other programs.
.TP
.B ~/.cache/ChimeraX
Directory for cached information.  May be removed, but history will be lost.
.TP
.B ~/.config/ChimeraX
Directory for configuration information.
Has preferences and information needed to uninstall cleanly.
.\"SH AUTHORS
.\".SH "SEE ALSO"
