name: Restore cached Python or download it
description: Restore cached Python or download it

inputs:
  platform:
    description: platform the artifact was built for (windows, macos, linux)
    required: true
  architecture:
    description: architecture of the wheel to be downloaded
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore cached PyQt6 and PyQt6-WebEngine (Linux)
      id: cache-pyqt6-linux
      if: ${{ inputs.platform == 'linux' }}
      uses: actions/cache@v4
      with:
        path: |
          prereqs/Python/python-3.11.4.tar.xz
        key: ${{ runner.os }}-${{ inputs.architecture }}-python

    - name: Restore cached PyQt6 and PyQt6-WebEngine (Windows)
      id: cache-pyqt6-windows
      if: ${{ inputs.platform == 'windows' }}
      uses: actions/cache@v4
      with:
        path: |
          prereqs/Python/python-3.11.4-win-amd64.tar.bz2
        key: ${{ runner.os }}-${{ inputs.architecture }}-python

    - name: Restore cached PyQt6 and PyQt6-WebEngine (macOS)
      id: cache-pyqt6-macos
      if: ${{ inputs.platform == 'macos' }}
      uses: actions/cache@v4
      with:
        path: |
          prereqs/Python/python-3.11.4-mac.tar.bz2
        key: ${{ runner.os }}-${{ inputs.architecture }}-python

    - name: Fetch PyQt
      shell: bash
      if: ${{ steps[format('cache-pyqt6-{0}', inputs.platform)].outputs.cache-hit != 'true' }}
      run: |
        if [ "${{ inputs.platform }}" = "linux" ] ; then
          curl https://www.rbvi.ucsf.edu/chimerax/data/prereqs/python/Python-3.11.4.tar.xz -O -J
          mv Python* prereqs/Python/
        fi
        if [ "${{ inputs.platform }}" = "macos" ] ; then
          curl https://www.rbvi.ucsf.edu/chimerax/data/prereqs/python/python-3.11.4-mac.tar.bz2 -O -J
          mv python* prereqs/Python/
        fi
        if [ "${{ inputs.platform }}" = "windows" ] ; then
          curl https://www.rbvi.ucsf.edu/chimerax/data/prereqs/python/python-3.11.4-win-amd64.tar.bz2 -O -J
          mv python* prereqs/Python/
        fi
