name: Download LCD Linux bundles from Plato
description: Download lowest common denominator bundles for Linux builds

inputs:
  platform:
    description: platform the artifact was built for (windows, macos, linux)
    required: true
  cache_key:
    description: remote cache key
    required: true
  build_type:
    description: one of preview, production, daily, staging
    required: true
  # TODO
  #architecture:
  #  description: architecture of the wheel to be downloaded
  #  required: true

runs:
  using: "composite"
  steps:
    - name: Mask input parameters
      shell: bash
      run: |
        export PREBUILT_CACHE_KEY=${{ inputs.cache_key }}
        echo "::add-mask::$PREBUILT_CACHE_KEY"

    - name: Fetch the bundles
      shell: bash
      run: |
        export BUNDLE_ARCHIVE_URL="https://preview.rbvi.ucsf.edu/chimerax/cgi-bin/get_bundles.py?platform=${{ inputs.platform }}&build_type=${{ inputs.build_type }}" # TODO &architecture=foo
        curl -H "X-API-KEY: ${{ inputs.cache_key }}" ${BUNDLE_ARCHIVE_URL} -O -J
