# -----------------------------------------------------------------------------
# Gaussian cube data generated by Gaussian 98.
#
def open(path):

  from gaussian_grid import read_gaussian_file
  return read_gaussian_file(path)
