name: Restore cached looking_glass dependencies or download them
description: Restore cached looking_glass dependencies or download them

runs:
  using: "composite"
  steps:
    - name: Restore cached looking_glass dependency sources
      id: cache-holoplaycore
      uses: actions/cache@v4
      with:
        path: |
          src/bundles/looking_glass/holoplaycore-0.1.0.tar.gz
        key: holoplaycore-source-zip-file

    - name: Fetch holoplaycore
      shell: bash
      if: ${{ steps.cache-holoplaycore.outputs.cache-hit != 'true' }}
      run: |
        curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/lookingglass/holoplaycore-0.1.0.tar.gz
        mv holoplaycore* src/bundles/looking_glass/
