name: Restore cached PyQt6 or download it
description: Restore cached PyQt6 or download it

inputs:
  platform:
    description: platform the artifact was built for (windows, macos, linux)
    required: true
  cache_key:
    description: remote cache key
    required: true
  architecture:
    description: architecture of the wheel to be downloaded
    required: true

runs:
  using: "composite"
  steps:
    - name: Mask input parameters
      shell: bash
      run: |
        export PREBUILT_CACHE_KEY=${{ inputs.cache_key }}
        echo "::add-mask::$PREBUILT_CACHE_KEY"

    - name: Restore cached PyQt6 and PyQt6-WebEngine (Linux)
      id: cache-pyqt6-linux
      if: ${{ inputs.platform == 'linux' }}
      uses: actions/cache@v4
      with:
        path: |
          prereqs/PyQt/PyQt6_commercial-6.7.1-1-cp38-abi3-manylinux_2_28_x86_64.whl
          prereqs/PyQt/PyQt6_WebEngine_commercial-6.7.0-cp38-abi3-manylinux_2_28_x86_64.whl
        key: ${{ runner.os }}-${{ inputs.architecture }}-pyqt6

    - name: Restore cached PyQt6 and PyQt6-WebEngine (Windows)
      id: cache-pyqt6-windows
      if: ${{ inputs.platform == 'windows' }}
      uses: actions/cache@v4
      with:
        path: |
          prereqs/PyQt/PyQt6_commercial-6.7.1-cp38-abi3-win_amd64.whl
          prereqs/PyQt/PyQt6_WebEngine_commercial-6.7.0-cp38-abi3-win_amd64.whl
        key: ${{ runner.os }}-${{ inputs.architecture }}-pyqt6

    - name: Restore cached PyQt6 and PyQt6-WebEngine (macOS)
      id: cache-pyqt6-macos
      if: ${{ inputs.platform == 'macos' }}
      uses: actions/cache@v4
      with:
        path: |
          prereqs/PyQt/PyQt6_commercial-6.7.1-cp38-abi3-macosx_11_0_universal2.whl
          prereqs/PyQt/PyQt6_WebEngine_commercial-6.7.0-cp38-abi3-macosx_10_14_universal2.whl
        key: ${{ runner.os }}-${{ inputs.architecture }}-pyqt6

    - name: Fetch PyQt
      shell: bash
      if: ${{ steps[format('cache-pyqt6-{0}', inputs.platform)].outputs.cache-hit != 'true' }}
      run: |
        if [ "${{ inputs.platform }}" = "linux" ] ; then 
          export PYQT_VERSION=6.7.1-1
        else
          export PYQT_VERSION=6.7.1
        fi
        export PYQTWE_VERSION=6.7.0
        export PYQT_URL="https://preview.rbvi.ucsf.edu/chimerax/cgi-bin/get_pyqt.py?platform=${{ inputs.platform }}&version=${PYQT_VERSION}&webengine=false&architecture=${{ inputs.architecture }}"
        export PYQTWE_URL="https://preview.rbvi.ucsf.edu/chimerax/cgi-bin/get_pyqt.py?platform=${{ inputs.platform }}&version=${PYQTWE_VERSION}&webengine=true&architecture=${{ inputs.architecture }}"
        curl -H "X-API-KEY: ${{ inputs.cache_key }}" ${PYQT_URL} -O -J
        curl -H "X-API-KEY: ${{ inputs.cache_key }}" ${PYQTWE_URL} -O -J
        mv PyQt6*.whl prereqs/PyQt/
