#!/bin/bash

# Handle arguments
if [ $# -gt 0 ]; then
	actions=$*
else
	actions="install"
fi

# $target is where the webapp (wsgi + html) is installed
# $chimera2 is the path to the chimera2 tree relative to $target
target=../../build/webapp
chimera2=..

# Execute actions in order
for action in $actions; do
	case $action in

	  install )
		#echo Installing to $target
		if [ ! -e $target ]; then
			mkdir -p $target
		fi

		# Create symlink to repo build tree
		rm -f $target/chimera2
		ln -s $chimera2 $target/chimera2

		# Copy local files
		local_files="chimera2.wsgi webapp_backend.py"
		rsync -Cav --exclude=\*.swp $local_files $target
		other_files="../llgr/webgl webapp_client/"
		rsync -Cav --exclude=\*.swp $other_files $target/www

		# Make sure some files are owned by user Apache
		if [ ! -e $target/sessions ]; then
			mkdir $target/sessions
		fi
		if which audit > /dev/null 2>&1; then
			audit apachedir $target/sessions
		fi
		;;

	  clean )
	  	echo Removing $target
		rm -rf $target
		;;

	  * )
	  	echo "unknown command" $action
		;;

	esac
done
