name: Upload LCD Linux Include Folder to Plato
description: Upload the include directory from the lowest common denominator Linux build
# That's the platform we support that ships with the lowest version of glibc

inputs:
  deploy_key:
    description: deploy key
    required: true
  platform:
    description: the OS
    required: true
  build_type:
    description: one of 'daily', 'preview', 'production', 'staging'
    required: true

runs:
  using: "composite"
  steps:
    - name: Mask input parameters
      shell: bash
      run: |
        export PREBUILT_CACHE_KEY=${{ inputs.deploy_key }}
        echo "::add-mask::$PREBUILT_CACHE_KEY"

    - name: Upload the bundles
      shell: bash
      run: |
        tar -cvzf ${{ inputs.platform }}-include.tar.gz -C build include
        curl -v -F "key=${{ inputs.deploy_key }}" -F "platform=${{ inputs.platform }}" -F "build_type=${{ inputs.build_type }}" -F "file=@$GITHUB_WORKSPACE/${{ inputs.platform }}-include.tar.gz" https://preview.rbvi.ucsf.edu/chimerax/cgi-bin/upload_includes.py
