[build-system]
requires = [
  "ChimeraX-BundleBuilder>=1.4.0",
  "ChimeraX-Core ~=1.0",
]
build-backend = "chimerax.bundle_builder.cx_pep517"

[project]
name = "ChimeraX-SpaceNavigator"
version = "1.0"
license = { text = "Free for non-commercial use" }
authors = [{ name = "UCSF RBVI", email = "chimerax@cgl.ucsf.edu" }]
description = "Space Navigator device support"
dependencies = [
  "ChimeraX-Core ~=1.0",
  "ChimeraX-Geometry ~=1.0",
]
dynamic = ["classifiers", "requires-python"]

[project.readme]
content-type = "text"
text = """This bundle allows using 3dconnexion space navigator devices to move models."""

[project.urls]
Home = "https://www.rbvi.ucsf.edu/chimerax/"

[tool.chimerax]
min-session-version = 1
max-session-version = 1
categories = ["General"]
classifiers = ["Development Status :: 2 - Pre-Alpha"]

[tool.chimerax.command."device snav"]
category = "General"
description = "Control SpaceNavigator device"

[tool.chimerax.extension._spacenavigator.platform.mac]
sources = [
  "spacenav.cpp",
]
include-dirs = [
  "/Library/Frameworks/3DconnexionClient.framework/Versions/Current/Headers",
  "src/include",
]
include-modules = [
  "chimerax.core",
]
library-modules = [
  "chimerax.core",
]
framework-dirs = [
  "/Library/Frameworks/",
]
frameworks = [
  "3DconnexionClient",
]


