# vim: syntax=config:
brew "netcdf"
brew "hdf5"    # tables
brew "lz4"     # tables
brew "c-blosc" # tables
brew "autoconf"
brew "automake"
brew "libtool"
# if installing scipy from source
brew "openblas"
brew "jq"

brew "python@3.10"
