name: Package Windows
description: Package ChimeraX for Windows

inputs:
  build_certificate:
    description: base64 encoded signing certificate
    required: true
  cert_password:
    description: signing certificate password
    required: true

runs:
  using: "composite"
  steps:
    - name: Mask input parameters
      shell: bash
      run: |
        export WINDOWS_SIGNING_PASS=${{ inputs.cert_password }}
        export WINDOWS_SIGNING_CERT=${{ inputs.build_certificate }}
        echo "::add-mask::$WINDOWS_SIGNING_CERT"
        echo "::add-mask::$WINDOWS_SIGNING_PASS"
        echo WINDOWS_SIGNING_CERT=$WINDOWS_SIGNING_CERT >> $GITHUB_ENV
        echo WINDOWS_SIGNING_PASS=$WINDOWS_SIGNING_PASS >> $GITHUB_ENV

    - name: Sign the application
      shell: bash
      run: |
        echo $WINDOWS_SIGNING_CERT | base64 --decode > CodeSign.pfx
        AUTOMATIC_DISCOVERY=1 . ./vsvars.sh && ./utils/build/windows/build_package . $WINDOWS_SIGNING_PASS
        rm CodeSign.pfx
