# -----------------------------------------------------------------------------
# PROFEC data generated by AMBER 7.
#
def open(path):

  from profec_grid import PROFEC_Grid
  return [PROFEC_Grid(path)]
