PYPISERVER =	../Frameworks/Python.framework/Versions/Current/bin/pypi-server

all:	METADATA.json
	$(PYPISERVER) --disable-fallback `pwd`

METADATA.json:	update_metadata.py
	../bin/python3 update_metadata.py
