# vim: set expandtab shiftwidth=4 softtabstop=4:

# === UCSF ChimeraX Copyright ===
# Copyright 2016 Regents of the University of California.
# All rights reserved.  This software provided pursuant to a
# license agreement containing restrictions on its disclosure,
# duplication and use.  For details see:
# http://www.rbvi.ucsf.edu/chimerax/docs/licensing.html
# This notice must be embedded in or attached to all copies,
# including partial copies, of the software or any revisions
# or derivations thereof.
# === UCSF ChimeraX Copyright ===

commands = [
    'log warn false error false',
    'open 1mtx',
    'mmaker #1.1 to #1.2',
    'mmaker #1.1-5 to #1.6 alg sw matrix PAM-150 cutoff 5.0',
    'close',
    'open 3fx2',
    'hbonds',
    '~hbonds',
    'hbonds two true intrares false',
    'close',
    'open 1a0m',
    '~display /b',
    'style stick',
    'ribbon /b',
    'surface enclose #1 resolution 5',
    'surface close',
    'surface #1',
    'measure sasa /a',
    'measure buriedarea /a with /b',
    'color #1 bychain',
    'color @CA purple',
    'light soft',
    'camera field 30',
    'camera',
    'close #1',
    'open pdb:4hhb',
    'color /a@CB tan',
    'colordef wow green',
    'color /c wow',
    '~colordef wow',
    'contacts #1',
    'crossfade 10',
    'delete /c',
    '~display',
    'display /d',
    'display',
    'echo Here we are',
    'color #1 sequential chains palette rainbow',
    'color /a dodger blue target a',
    'open emdb:1080',
    'fitmap #1 in #2 resolution 10 metric correlation',
    'help fitmap',
    'ks ha',
    'ks rb',
    '2dlabel create x text "Look at this" size 36 xpos .2 ypos .8 color yellow',
    '2dlabel change x text "Great Scots"',
    '2dlabel delete x',
    'lighting',
    'lighting color red',
    'lighting full',
    'info',
    'log hide',
    'log show',
    'log error false',
    'material specular 1.2 exponent 100',
    'material shiny',
    'molmap #1 5 grid 1',
    'move y 1 20',
    'movie record super 3',
    'wait',
    'movie encode ~/Desktop/test_movie.mp4 quality high',
#    'vr on',
#    'vr off',
    'perframe "turn y 15" frames 10',
    'pwd',
    'roll z',
    'stop',
    'ribbon /b/c',
    '~disp /b/c',
    '~ribbon',
    'run "echo run run run"',
    'measure sasa /d',
#    'save ~/Desktop/test_image.jpg',  # JPEG support missing, bug #186
    'save ~/Desktop/test_image.png',
    'surface #1',
    'scolor #1 byatom',
    'scolor #1 map #2',
    'set bg gray silhouettes true',
    'device snav on fly true',
    'device snav off',
    'split #1',
    'style ball',
    'surface :46-80',
    'surf hide #1',
    'surf show #1',
    'close',
    'open 2bbv',
    'sym #1',
    'sym #1 as 4',
    'sym clear #1',
    'toolshed list',
    'toolshed reload',
    'toolshed hide \"Command Line Interface\"',
    'toolshed show \"Command Line Interface\"',
    'info models',
    'molmap #1 5 grid 1',
    'volume #3 level .05',
    'volume #3 color tan enclose 1e5',
    'vop gaussian #3 sdev 2',
    'vop subtract #3,4',
    'view',
    'echo finished test',
]
def run_commands(session, commands = commands):
    log = session.logger
    from chimerax.core.commands import run
    for c in commands:
        log.info('> ' + c)
        run(session, c)
