name: Restore cached plato pips or download them
description: Restore cached plato pips or download them

inputs:
  platform:
    description: platform the artifact was built for
    required: true
  architecture:
    description: architecture of the wheel to be downloaded
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore cached plato pips
      id: cache-plato-pips-linux
      if: ${{ inputs.platform }} == 'linux'
      uses: actions/cache@v4
      with:
        path: |
          prereqs/pips/tinyarray-1.2.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
        key: ${{ runner.os }}-${{ inputs.architecture}}-pips

    - name: Restore cached plato pips
      id: cache-plato-pips-windows
      if: ${{ inputs.platform }} == 'windows'
      uses: actions/cache@v4
      with:
        path: |
          prereqs/pips/tinyarray-1.2.4-cp311-cp311-win_amd64.whl
        key: ${{ runner.os }}-${{ inputs.architecture}}-pips

    - name: Restore cached plato pips
      id: cache-plato-pips-macos
      if: ${{ inputs.platform }} == 'macos'
      uses: actions/cache@v4
      with:
        path: |
          prereqs/pips/tinyarray-1.2.4-cp311-cp311-macosx_10_9_universal2.whl
          prereqs/pips/Cython-3.0.10-cp311-cp311-macosx_10_9_universal2.whl
        key: ${{ runner.os }}-${{ inputs.architecture}}-pips

    - name: Restore cached generic pips
      id: cache-plato-pips-generic
      uses: actions/cache@v4
      with:
        path: |
          prereqs/pips/grako-3.16.5-py2.py3-none-any.whl
          prereqs/pips/cxservices-1.2.3-py3-none-any.whl
          prereqs/pips/qtshim-1.0-py3-none-any.whl
        key: generic-plato-pips

    - name: Fetch platform specific pips
      shell: bash
      if: ${{ steps[format('cache-plato-pips-{0}', inputs.platform)].outputs.cache-hit != 'true' }}
      run: |
        if [ "${{ inputs.platform }}" = "linux" ] ; then
          curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/tinyarray/tinyarray-1.2.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
        fi
        if [ "${{ inputs.platform }}" = "macos" ] ; then
          curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/tinyarray/tinyarray-1.2.4-cp311-cp311-macosx_10_9_universal2.whl
          curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/cython/Cython-3.0.10-cp311-cp311-macosx_10_9_universal2.whl
        fi
        if [ "${{ inputs.platform }}" = "windows" ] ; then
          curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/tinyarray/tinyarray-1.2.4-cp311-cp311-win_amd64.whl
        fi
        mv tinyarray* prereqs/pips/

    - name: Fetch generic pips
      shell: bash
      if: ${{ steps.cache-plato-pips-generic.outputs.cache-hit != 'true' }}
      run: |
        curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/grako/grako-3.16.5-py2.py3-none-any.whl
        curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/cxservices/cxservices-1.2.3-production-py3-none-any.whl
        curl --silent --show-error --fail --insecure -O https://www.rbvi.ucsf.edu/chimerax/data/prereqs/qt/qtshim-1.0-py3-none-any.whl
        mv grako* prereqs/pips/
        mv cxservices* prereqs/pips/cxservices-1.2.3-py3-none-any.whl
        mv qtshim* prereqs/pips/
