name: Upload Linux docs to Plato
description: Upload docs

inputs:
  deploy_key:
    description: deploy key
    required: true

runs:
  using: "composite"
  steps:
    - name: Mask input parameters
      shell: bash
      run: |
        export PREBUILT_CACHE_KEY=${{ inputs.deploy_key }}
        echo "::add-mask::$PREBUILT_CACHE_KEY"

    - name: Upload the docs
      shell: bash
      run: |
        export DOC_DIR=$(git rev-parse --show-toplevel)/ChimeraX.app/share/docs/
        tar -cvzf chimerax-docs.tar.gz -C $DOC_DIR .
        curl -v -F "key=${{ inputs.deploy_key }}" -F "file=@$GITHUB_WORKSPACE/chimerax-docs.tar.gz" https://preview.rbvi.ucsf.edu/chimerax/cgi-bin/upload_docs.py
