name: Restore cached ambertools or download it
description: Restore cached ambertools or download it

inputs:
  platform:
    description: platform the artifact was built for (windows, macos, linux)
    required: true
  architecture:
    description: architecture of the wheel to be downloaded
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore cached ambertools (Linux)
      id: cache-ambertools-linux
      if: ${{ inputs.platform == 'linux' }}
      uses: actions/cache@v4
      with:
        path: |
          prereqs/ambertools/ambertools-20-Linux-Rocky-8.10.tar.bz2
        key: ${{ runner.os }}-${{ inputs.architecture }}-ambertools

    - name: Restore cached ambertools and PyQt6-WebEngine (Windows)
      id: cache-ambertools-windows
      if: ${{ inputs.platform == 'windows' }}
      uses: actions/cache@v4
      with:
        path: |
          prereqs/ambertools/ambertools-20-Windows.tar.bz2
        key: ${{ runner.os }}-${{ inputs.architecture }}-ambertools

    - name: Restore cached ambertools (macOS)
      id: cache-ambertools-macos
      if: ${{ inputs.platform == 'macos' }}
      uses: actions/cache@v4
      with:
        path: |
          prereqs/ambertools/ambertools-20-Darwin.tar.bz2
          prereqs/ambertools/ambertools-flibs-20-Darwin.tar.bz2
        key: ${{ runner.os }}-${{ inputs.architecture }}-ambertools

    - name: Fetch ambertools
      shell: bash
      if: ${{ steps[format('cache-ambertools-{0}', inputs.platform)].outputs.cache-hit != 'true' }}
      run: |
        if [ "${{ inputs.platform }}" = "linux" ] ; then
          curl https://www.rbvi.ucsf.edu/chimerax/data/prereqs/ambertools/ambertools-20-Linux-Rocky-8.10.tar.bz2 -O -J
        fi
        if [ "${{ inputs.platform }}" = "macos" ] ; then
          curl https://www.rbvi.ucsf.edu/chimerax/data/prereqs/ambertools/ambertools-flibs-20-Darwin.tar.bz2 -O -J
          curl https://www.rbvi.ucsf.edu/chimerax/data/prereqs/ambertools/ambertools-20-Darwin.tar.bz2 -O -J
        fi
        if [ "${{ inputs.platform }}" = "windows" ] ; then
          curl https://www.rbvi.ucsf.edu/chimerax/data/prereqs/ambertools/ambertools-20-Windows.tar.bz2 -O -J
        fi
        mv ambertools* prereqs/ambertools/
