[build-system]
requires = ["setuptools", "ChimeraX-BundleBuilder"]
build-backend = "chimerax.bundle_builder.cx_pep517"

[project]
name = "ChimeraX-TaskManager"
license = { text = "Free for non-commercial use" }
authors= [{name = "UCSF RBVI", email="chimerax@cgl.ucsf.edu"}]
description = "Manage background tasks in ChimeraX"
dependencies = [
	"ChimeraX-Core ~=1.0"
	, "ChimeraX-UI ~=1.0"
]
dynamic = ["classifiers", "requires-python", "version"]

[project.readme]
content-type = "text"
text = """Manage background tasks in ChimeraX"""
	
[project.urls]
Home = "https://www.rbvi.ucsf.edu/chimerax/"

[tool.setuptools.dynamic]
version = { attr = "src.__version__" }

[chimerax]
min-session-version = 1
max-session-version = 1
categories = ["User Interface"]
classifiers = ["Development Status :: 2 - Pre-Alpha"]

[chimerax.tool."Task Manager"]
category = "Utilities"
description = "Visualize open tasks"

[chimerax.command.taskman]
category = "Utilities"
description = "Visualize open tasks"
