name: Build and test with changed prereqs

on: workflow_call

jobs:
  rebuild-changed-prereqs:
    name: Rebuild changed prereqs
    uses: ./.github/workflows/prereqs.yml
  rebuild-changed-bundles:
    needs: rebuild-changed-prereqs
    name: Rebuild changed bundles
    uses: ./.github/workflows/bundle-changes.yml
  rebuild-changed-apps:
    needs: rebuild-changed-prereqs
    name: Rebuild changed apps
    uses: ./.github/workflows/srcapps.yml
  build-and-test-ubuntu:
    needs:
      [rebuild-changed-prereqs, rebuild-changed-bundles, rebuild-changed-apps]
    name: Build ChimeraX
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get upgrade -y && ${PWD}/utils/set_up_ubuntu.sh
      - run: make build-minimal
      - name: Run the traditional test suite
        run: make test
      - run: make venv
      - name: Run Pytest
        run: source .venv/bin/activate && python3 -m pip install pytest && pytest
  build-and-test-rocky8-docker:
    needs:
      [rebuild-changed-prereqs, rebuild-changed-bundles, rebuild-changed-apps]
    runs-on: ubuntu-20.04
    container:
      image: rockylinux:8
    env:
      SHELL: /bin/bash
      PATH: /usr/bin:/usr/sbin:/bin:/sbin
    steps:
      - run: export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
      - run: dnf update -y
      - run: dnf install -y git-all
      - uses: actions/checkout@v4
      # buildinfo.py breaks without this
      - run: chown -R $(id -u):$(id -g) $PWD
      - run: ${PWD}/utils/set_up_centos.sh
      - run: source /opt/rh/gcc-toolset-10/enable && make -f Makefile.centos build-minimal
      - name: Run the traditional test suite
        run: make test
      - run: make venv
      - name: Run Pytest
        run: source .venv/bin/activate && python3 -m pip install pytest && pytest
  build-and-test-macos:
    needs:
      [rebuild-changed-prereqs, rebuild-changed-bundles, rebuild-changed-apps]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build-minimal
      - name: Run the traditional test suite
        run: make test
      - run: make venv
      - name: Run Pytest
        run: source .venv/bin/activate && python3 -m pip install pytest && pytest
      - name: Sign the macOS package
        uses: ./utils/ci/sign_macos
  build-and-test-windows:
    needs:
      [rebuild-changed-prereqs, rebuild-changed-bundles, rebuild-changed-apps]
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-imagemagick mingw-w64-x86_64-binutils mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-objc mingw-w64-x86_64-gcc-fortran rsync patch unzip openssh make
      - run: GITHUB_ACTIONS_CI=1 . ./vsvars.sh && make build-minimal
      - name: Run the traditional test suite
        run: GITHUB_ACTIONS_CI=1 . ./vsvars.sh && make test
      - name: Run Pytest
        run: make venv && . ./.venv/Scripts/activate && python3 -m pip install pytest && pytest
