name: Build ChimeraX

on:
  push:
    branches: [ setup_github_workflows ]
  pull_request:
    branches: [ setup_github_workflows ]
  

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ChimeraX
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: Update apt 
        run: sudo apt-get update && sudo apt-get upgrade
      - name: Install Dependencies
        run: |
          sudo apt-get install -y --no-install-recommends \
          language-selector-common ffmpeg vim-nox \
          build-essential g++ gfortran \
          chrpath patch openssh-client rsync ca-certificates \
          make autoconf automake libtool pkg-config \
          flex bison yasm unzip tar fakeroot curl wget \
          python2.7 \
          imagemagick \
          libasound2-dev \
          libatk1.0-dev \
          libbz2-dev \
          libcairo2-dev \
          libcups2-dev \
          libdbus-1-dev \
          libegl1-mesa-dev \
          libexpat1-dev \
          libffi-dev \
          libfftw3-dev \
          libfreetype6-dev \
          libgdk-pixbuf2.0-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgtk-3-dev \
          libhdf5-dev \
          libicu-dev \
          libjpeg-dev \
          liblzma-dev \
          libmysqlclient-dev \
          libnss3-dev \
          libosmesa6-dev \
          libpango1.0-dev \
          libpcre3-dev \
          libpng-dev \
          libpulse-dev \
          libssl-dev \
          libtiff-dev \
          libx11-dev \
          libxcomposite-dev \
          libxcursor-dev \
          libxft-dev \
          libxi-dev \
          libxmu-dev \
          libxpm-dev \
          libxrandr-dev \
          libxslt1-dev \
          libxss-dev \
          libxt-dev \
          libxtst-dev \
          llvm-dev \
          x11proto-scrnsaver-dev \
          xdg-utils \
          zlib1g-dev
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Compile
        run: make build-from-scratch
