name: Release
on:
  workflow_dispatch:

jobs:
  #build-rocky8-docker:
  #  name: Build ChimeraX for Rocky 8
  #  uses: ./.github/workflows/rocky8_build.yml
  #  with:
  #    branch: master
  #    release_type: production
  #  secrets: inherit
  #build-rocky9-docker:
  #  name: Build ChimeraX for Rocky 9
  #  needs: [build-rocky8-docker]
  #  uses: ./.github/workflows/rocky9_build.yml
  #  with:
  #    branch: master
  #    release_type: production
  #  secrets: inherit
  #build-ubuntu:
  #  name: Build ChimeraX for Ubuntu
  #  needs: [build-rocky8-docker]
  #  uses: ./.github/workflows/ubuntu_build.yml
  #  with:
  #    branch: master
  #    release_type: production
  #  secrets: inherit
  #build-flatpak:
  #  name: Build ChimeraX FlatPak
  #  needs: [build-rocky8-docker]
  #  uses: ./.github/workflows/flatpak_build.yml
  #  with:
  #    branch: master
  #    release_type: production
  #  secrets: inherit
  #build-flatpak-arm:
  #  name: Build ARM ChimeraX FlatPak
  #  uses: ./.github/workflows/flatpak_arm_build.yml
  #  with:
  #    branch: master
  #    release_type: production
  #  secrets: inherit
  #build-arm-macos:
  #  name: Build ChimeraX for arm64 macOS
  #  uses: ./.github/workflows/mac_arm_build.yml
  #  with:
  #    branch: master
  #    release_type: production
  #  secrets: inherit
  #build-intel-macos:
  #  name: Build ChimeraX for Intel macOS
  #  uses: ./.github/workflows/mac_intel_build.yml
  #  with:
  #    branch: master
  #    release_type: production
  #  secrets: inherit
  #build-mac-universal:
  #  name: Build Universal ChimeraX for macOS
  #  needs: [build-arm-macos, build-intel-macos]
  #  uses: ./.github/workflows/mac_universal_build.yml
  #  with:
  #    branch: master
  #    release_type: production
  #  secrets: inherit
  #build-windows:
  #  name: Build ChimeraX for Windows
  #  uses: ./.github/workflows/windows_build.yml
  #  with:
  #    branch: master
  #    release_type: production
  #  secrets: inherit
  build-wheels:
    name: Build ChimeraX wheels
    uses: ./.github/workflows/wheels.yml
    with:
      branch: develop
      release_type: production
    secrets: inherit
