name: Test Flatpak build
on:
  workflow_dispatch:

jobs:
  build-flatpak:
    name: Build ChimeraX Flatpak
    runs-on: ubuntu-20.04
    env:
      SHELL: /bin/bash
      PATH: /usr/bin:/usr/sbin:/bin:/sbin
      PYOPENGL_PLATFORM: egl
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Fetch PyQt6 and PyQt6-WebEngine from Plato
        uses: ./utils/ci/cache_pyqt
        with:
          platform: linux
          architecture: x86_64
          cache_key: ${{ secrets.PREBUILT_CACHE_SECRET }}
      - uses: ./utils/ci/download_lcd_linux_bundles
        with:
          platform: linux
          cache_key: ${{ secrets.PREBUILT_CACHE_SECRET }}
          build_type: daily
      - uses: ./utils/ci/download_lcd_linux_include
        with:
          platform: linux
          cache_key: ${{ secrets.PREBUILT_CACHE_SECRET }}
          build_type: daily
      - run: chown -R $(id -u):$(id -g) $PWD
      - name: Unpack the bundles to build/sync
        run: |
          mkdir wheels
          tar -xvf linux-bundles.tar.gz -C wheels
      - name: Unpack the include tarball to include
        run: |
          tar -xvf linux-include.tar.gz
      - name: Build the rest of ChimeraX
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: chimerax.flatpak
          manifest-path: github-flatpak.yaml
          cache-key: flatpak-builder-${{ github.sha }}
      # For now, we're skipping tests for the Flatpak
      - name: Upload ChimeraX
        uses: ./utils/ci/upload_artifact
        with:
          artifact_path: chimerax.flatpak
          full_build: true
          release_type: github-techpreview
          platform: flatpak
          deploy_key: ${{ secrets.PREBUILT_CACHE_SECRET }}
